language: java

sudo: false

jdk:
  - oraclejdk8

install: true

script:
  - echo skipping sudo apt-get update && echo skipping sudo apt-get install oracle-java8-installer
  - lsb_release -a
  - uname -a
  - java -version
  - mvn -version
  - mvn verify
  
notifications:
  email:
    - william.shackleford@nist.gov
    - wshackle@gmail.com

# Change this to your needs
#script: ./configure && make && make check && cd rcsjava_maven/rcslib && mvn -version && mvn -e compile &&  mvn test && mvn verify 

